dataset:
  basedir: cache/nerf_synthetic/chair
  cachedir: cache/chaircache200
  far: 5
  half_res: false
  near: 2
  no_ndc: true
  testskip: 1
  type: blender
experiment:
  id: chair
  logdir: logs
  print_every: 2500
  randomseed: 42
  save_every: 10000
  train_iters: 200000
  validate_every: 2500
models:
  coarse:
    hidden_size: 128
    include_input_dir: true
    include_input_xyz: true
    log_sampling_dir: true
    log_sampling_xyz: true
    num_encoding_fn_dir: 4
    num_encoding_fn_xyz: 10
    num_layers: 8
    skip_connect_every: 3
    type: FlexibleNeRFModel
    use_viewdirs: true
  fine:
    hidden_size: 128
    include_input_dir: true
    include_input_xyz: true
    log_sampling_dir: true
    log_sampling_xyz: true
    num_encoding_fn_dir: 4
    num_encoding_fn_xyz: 10
    num_layers: 8
    skip_connect_every: 3
    type: FlexibleNeRFModel
    use_viewdirs: true
nerf:
  alpha1: 0.1
  alpha2: 0.01
  beta1: 1.0
  beta2: 0.1
  encode_direction_fn: positional_encoding
  encode_position_fn: positional_encoding
  train:
    chunksize: 90112
    lindisp: false
    num_coarse: 64
    num_fine: 128
    num_random_rays: 2048
    perturb: true
    radiance_field_noise_std: 0.2
    white_background: false
  use_viewdirs: true
  validation:
    chunksize: 20000
    img: 62
    img_alternative_view: 110
    lindisp: false
    num_coarse: 64
    num_fine: 128
    perturb: false
    radiance_field_noise_std: 0.0
    white_background: false
optimizer:
  lr: 0.005
  type: Adam
scheduler:
  lr_decay: 250
  lr_decay_factor: 0.1
